package com.roshni.games.core.utils.error

/**
 * Enumeration of all possible error types in the gaming platform
 */
enum class ErrorType {
    // Network related errors
    NETWORK_ERROR,
    NETWORK_TIMEOUT,
    NETWORK_UNAVAILABLE,
    NETWORK_AUTHENTICATION_FAILED,
    NETWORK_SERVER_ERROR,
    NETWORK_CLIENT_ERROR,
    NETWORK_RATE_LIMITED,

    // Gameplay related errors
    GAMEPLAY_INVALID_MOVE,
    GAMEPLAY_RULE_VIOLATION,
    GAMEPLAY_STATE_INVALID,
    GAMEPLAY_SESSION_EXPIRED,
    GAMEPLAY_SAVE_FAILED,
    GAMEPLAY_LOAD_FAILED,
    GAMEPLAY_SYNC_FAILED,

    // Permission related errors
    PERMISSION_DENIED,
    PERMISSION_NOT_GRANTED,
    PERMISSION_RESTRICTED,
    PERMISSION_EXPIRED,
    PERMISSION_SCOPE_INSUFFICIENT,

    // Validation related errors
    VALIDATION_INVALID_INPUT,
    VALIDATION_MISSING_REQUIRED_FIELD,
    VALIDATION_FORMAT_INVALID,
    VALIDATION_RANGE_OUT_OF_BOUNDS,
    VALIDATION_CONSTRAINT_VIOLATION,

    // System related errors
    SYSTEM_OUT_OF_MEMORY,
    SYSTEM_STORAGE_FULL,
    SYSTEM_BATTERY_LOW,
    SYSTEM_OVERHEATED,
    SYSTEM_HARDWARE_ERROR,

    // Security related errors
    SECURITY_AUTHENTICATION_FAILED,
    SECURITY_AUTHORIZATION_FAILED,
    SECURITY_SESSION_EXPIRED,
    SECURITY_TOKEN_INVALID,
    SECURITY_ENCRYPTION_FAILED,

    // Feature related errors
    FEATURE_NOT_AVAILABLE,
    FEATURE_NOT_ENABLED,
    FEATURE_CONFIGURATION_INVALID,
    FEATURE_DEPENDENCY_MISSING,
    FEATURE_EXECUTION_FAILED,

    // Data related errors
    DATA_NOT_FOUND,
    DATA_CORRUPTED,
    DATA_VERSION_MISMATCH,
    DATA_MIGRATION_FAILED,
    DATA_BACKUP_FAILED,

    // User related errors
    USER_NOT_AUTHENTICATED,
    USER_ACCOUNT_SUSPENDED,
    USER_AGE_RESTRICTION,
    USER_PARENTAL_CONTROLS_ACTIVE,

    // Generic errors
    UNKNOWN_ERROR,
    UNEXPECTED_ERROR,
    OPERATION_CANCELLED,
    DEPENDENCY_FAILED
}